[build-system]
requires = ["setuptools>=50",
            "wheel",
            "toml",
            "setuptools_scm[toml]>=3.4",
            "setuptools_scm_git_archive"]

[tool.setuptools_scm]
write_to = "nkshow/_version.py"
